config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  devise_for :users, path: 'users', controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root to: 'home#index'

  resources :shipping_companies, only: [:index, :show, :new, :create, :edit, :update] do

    resources :vehicles, only: [:index, :new, :create, :edit, :update]
    resources :volume_prices, only: [:index, :new, :create]
    resources :weight_prices, only: [:index, :new, :create]
    resources :delivery_times, only: [:index, :new, :create]
    get 'sc_orders', on: :member
    collection do
      get 'budget_form'
      get 'budget_search'
      get 'tracking_form'
      get 'tracking_search'
    end
    resources :orders, only: [:show, :update] do
      resources :route_updates, only: [:index, :new, :create]
      member do
        post 'flag_button'
        patch 'approve'
      end
    end

  end



  resources :orders, only: [:index, :new, :create]

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :shipping_company, optional: true
  belongs_to :vehicle, optional: true
  has_many :route_updates

  enum status: { pending: 0, rejected: 5, approved: 10, delivered: 15 }

  before_validation :generate_id_code

  validates :origin_address, :product_length, :product_height, :product_width, :product_weight, :destination_address, :status, presence: true
  validates :product_length, :product_height, :product_width, :product_weight, numericality: { greater_than_or_equal_to: 0 }

  private

  def generate_id_code
    if self.id_code.nil?
      self.id_code = SecureRandom.alphanumeric(15).upcase
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :flag_button, :approve, :update]
  before_action :only_admin_or_user_allowed, only: [:show, :flag_button, :approve, :update]
  before_action :order_params, only: [:create]
  before_action :set_order, only: [:show, :flag_button, :approve, :update]

  def index
    @orders = Order.all
  end
  
  def new
    @order = Order.new
    @shipping_companies = ShippingCompany.all
  end

  def create
    @shipping_companies = ShippingCompany.all
    @order = Order.new(order_params)
    if @order.save
      flash[:notice] = 'Ordem de Serviço cadastrada com sucesso.'
      redirect_to orders_path
    else
      flash.now[:notice] = 'Não foi possível cadastrar a Ordem de Serviço.'
      render 'new'
    end
  end

  def show
    @flag_button_clicked = false
    if user_signed_in? && current_user.shipping_company != @order.shipping_company
      flash[:notice] = 'Usuário, você foi redirecionado por tentar visualizar uma Ordem de Serviço de outra Transportadora.'
      redirect_to root_path
    end
  end

  def flag_button
    @flag_button_clicked = true
    render 'show'
  end

  def update
    @order = Order.find(params[:id])
    @order.vehicle = Vehicle.find(params[:order][:vehicle_id])
    if @order.save()
      @order.approved!
      flash[:notice] = 'Ordem de Serviço aprovada com sucesso.'

      # Cria (se ainda nao tiver sido criado) e vincula route_update:
      if RouteUpdate.where(order: @order).any? == false
        date = Time.now.strftime("%d/%m/%Y")
        time = Time.now.strftime("%H:%M")
        origin_location = @order.origin_address
        route_update = RouteUpdate.create!(date: date, time: time, current_location: origin_location, order: @order)
      end
      redirect_to  shipping_company_order_path(@order.shipping_company.id, @order.id)
    else
      flash.now[:notice] = 'Não foi possível aprovar a Ordem de Serviço.'
      render 'show'
    end
  end

  def approve
    @order.approved!
    redirect_to shipping_company_order_path(@order.shipping_company_id, @order.id)
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:origin_address, :product_length, :product_height, :product_width, :product_weight, :destination_address, :shipping_company_id)
  end

  def only_admin_or_user_allowed
    if !admin_signed_in? && !user_signed_in?
      flash[:notice] = 'Área permitida somente para Admins e Usuários'
      redirect_to root_path
    end
  end

end

app/views/orders/index.html.erb
<h2>Ordens de Serviço</h2>
<%= link_to 'Cadastrar Nova Ordem de Serviço', new_order_path %>

<% if Order.any? %>
  <table style="text-align: center;">
    <tr>
      <th>Código</th>
      <th>Status</th>
      <th>Endereço de Origem</th>
      <th>Endereço de Destino</th>
      <th>Transportadora</th>
      <th>Veículo</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id_code %></td>
        <td><%= order.status %></td>
        <td><%= order.origin_address %></td>
        <td><%= order.destination_address %></td>
        <% if order.shipping_company == nil %>
          <td>Sem transportadora</td>
        <% else %>
          <td><%= order.shipping_company.brand_name %></td>
        <% end %>
        <% if order.vehicle == nil %>
          <td>Sem Veículo</td>
        <% else %>
          <td><%= order.vehicle.make %> <%= order.vehicle.model %> <%= order.vehicle.year %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Nenhuma Ordem de Serviço Cadastrada.</p>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/orders/new.html.erb
<h2>Nova Ordem de Serviço</h2>

<%= form_with(model: @order) do |f| %>
  <div>
    <%= f.label :origin_address %>
    <%= f.text_field :origin_address %>
    <%= @order.errors.full_messages_for(:origin_address)[0] if @order.errors.full_messages_for(:origin_address).any? %>
  </div>
  <div>
    <%= f.label :product_length %>
    <%= f.number_field :product_length, step: 0.01 %>
    <%= @order.errors.full_messages_for(:product_length)[0] if @order.errors.full_messages_for(:product_length).any? %>
  </div>
  <div>
    <%= f.label :product_height %>
    <%= f.number_field :product_height, step: 0.01 %>
    <%= @order.errors.full_messages_for(:product_height)[0] if @order.errors.full_messages_for(:product_height).any? %>
  </div>
  <div>
    <%= f.label :product_width %>
    <%= f.number_field :product_width, step: 0.01 %>
    <%= @order.errors.full_messages_for(:product_width)[0] if @order.errors.full_messages_for(:product_width).any? %>
  </div>
  <div>
    <%= f.label :product_weight %>
    <%= f.number_field :product_weight, step: 0.01 %>
    <%= @order.errors.full_messages_for(:product_weight)[0] if @order.errors.full_messages_for(:product_weight).any? %>
  </div>
  <div>
    <%= f.label :destination_address %>
    <%= f.text_field :destination_address %>
    <%= @order.errors.full_messages_for(:destination_address)[0] if @order.errors.full_messages_for(:destination_address).any? %>
  </div>
  <div>
    <%= f.label :shipping_company_id, 'Transportadora' %>
    <%= f.collection_select :shipping_company_id, @shipping_companies, :id, :brand_name %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
  
<% end %>

app/views/orders/show.html.erb
<h2>Transportadora <%= @order.shipping_company.brand_name %>: Ordem de Serviço <%= @order.id_code %></h2>

<% if @order.approved? %>
  <%= link_to 'Rota de entrega', shipping_company_order_route_updates_path(@order.shipping_company.id, @order.id) %>
<% end %>

<dl>
  <dt><strong>Status:</strong></dt>
  <dd><%= @order.status %></dd>
  <br>
  <dt><strong>Endereço para retirada:</strong></dt>
  <dd><%= @order.origin_address %></dd>
  <dt><strong>Endereço de destino:</strong></dt>
  <dd><%= @order.destination_address %></dd>
  <dt><strong>Peso do Produto:</strong></dt>
  <dd><%= @order.product_weight %></dd>
  <dt><strong>Comprimento do Produto:</strong></dt>
  <dd><%= @order.product_length %></dd>
  <dt><strong>Altura do Produto:</strong></dt>
  <dd><%= @order.product_height %></dd>
  <dt><strong>Largura do Produto:</strong></dt>
  <dd><%= @order.product_width %></dd>
  <dt><strong>Veículo:</strong></dt>
  <% if @order.vehicle.nil? %>
  <dd>Nenhum veículo vinculado</dd>
  <% else %>
  <dd><%= @order.vehicle.make %> <%= @order.vehicle.model %> <%= @order.vehicle.year %></dd>
  <% end %>
</dl>

<%= button_to 'Aprovar', flag_button_shipping_company_order_path(@order.shipping_company.id, @order.id) %>
<br>
<% if @flag_button_clicked %>
  <%= form_with(model: [@order.shipping_company, @order]) do |f| %>
    <div>
      <%= f.label :vehicle_id, 'Veículo' %>
      <%= f.collection_select :vehicle_id, @order.shipping_company.vehicles, :id, :model %>
    </div>
    <br>
    <div>
      <%= f.submit 'Vincular Veículo' %>
    </div>
  <% end %>
<% end %>
