config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  devise_for :users, path: 'users', controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root to: 'home#index'

  resources :shipping_companies, only: [:index, :show, :new, :create, :edit, :update] do

    resources :vehicles, only: [:index, :new, :create, :edit, :update]
    resources :volume_prices, only: [:index, :new, :create]
    resources :weight_prices, only: [:index, :new, :create]
    resources :delivery_times, only: [:index, :new, :create]
    get 'sc_orders', on: :member
    collection do
      get 'budget_form'
      get 'budget_search'
      get 'tracking_form'
      get 'tracking_search'
    end
    resources :orders, only: [:show, :update] do
      resources :route_updates, only: [:index, :new, :create]
      member do
        post 'flag_button'
        patch 'approve'
      end
    end

  end



  resources :orders, only: [:index, :new, :create]

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :shipping_company

  validates :id_plate, :make, :model, :year, :load_capacity, presence: true
  validates :id_plate, uniqueness: true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_shipping_company
  before_action :set_vehicle, only: [:edit, :update]
  before_action :only_admin_or_user_allowed

  def index
    @vehicles = Vehicle.where(shipping_company: @shipping_company)
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params())
    if @vehicle.save()
      flash[:notice] = 'Veículo cadastrado com sucesso.'
      redirect_to shipping_company_vehicles_path
    else
      flash.now[:notice] = 'Não foi possível cadastrar o veículo.'
      render 'edit'
    end
  end

  def edit; end

  def update
    if @vehicle.update(vehicle_params())
      flash[:notice] = 'Veículo atualizado com sucesso.'
      redirect_to shipping_company_vehicles_path(@shipping_company.id)
    else
      flash.now[:notice] = 'Não foi possível atualizar o veículo.'
      render 'new'
    end

  end

  private

  def set_shipping_company
    @shipping_company = ShippingCompany.find(params[:shipping_company_id])
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    vp = params.require(:vehicle).permit(:id_plate, :make, :model, :year, :load_capacity)
    vp.merge!({shipping_company: set_shipping_company()})
    return vp
  end

  def only_admin_or_user_allowed
    if !admin_signed_in? && !user_signed_in?
      flash[:notice] = 'Área permitida somente para Admins e Usuários'
      redirect_to root_path
    end
  end

end

app/views/vehicles/_form.html.erb
<%= form_with(model: [@shipping_company, @vehicle]) do |f| %>
  <div>
    <%= f.label :id_plate %>
    <%= f.text_field :id_plate %>
    <%= @vehicle.errors.full_messages_for(:id_plate)[0] if @vehicle.errors.full_messages_for(:id_plate).any? %>
  </div>
  <div>
    <%= f.label :make %>
    <%= f.text_field :make %>
    <%= @vehicle.errors.full_messages_for(:make)[0] if @vehicle.errors.full_messages_for(:make).any? %>
  </div>
  <div>
    <%= f.label :model %>
    <%= f.text_field :model %>
    <%= @vehicle.errors.full_messages_for(:model)[0] if @vehicle.errors.full_messages_for(:model).any? %>
  </div>
  <div>
    <%= f.label :year %>
    <%= f.text_field :year %>
    <%= @vehicle.errors.full_messages_for(:year)[0] if @vehicle.errors.full_messages_for(:year).any? %>
  </div>
  <div>
    <%= f.label :load_capacity %>
    <%= f.text_field :load_capacity %>
    <%= @vehicle.errors.full_messages_for(:load_capacity)[0] if @vehicle.errors.full_messages_for(:load_capacity).any? %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h2>Editar veículo <%= @vehicle.make %> <%= @vehicle.model %> <%= @vehicle.year %></h2>

<%= render partial: 'form' %>

<%= link_to 'Voltar', shipping_company_vehicles_path %>

app/views/vehicles/index.html.erb
<h2>Veículos Cadastrados</h2>
  <%= link_to 'Cadastrar Novo Veículo', new_shipping_company_vehicle_path(@shipping_company.id) %>
<% if @vehicles.any? %>
  <table>
    <tr>
      <th>Nome do veículo</th>
      <th>Placa</th>
      <th>Capacidade de carga (kg)</th>
    </tr>
    <% @vehicles.each do |v| %>
      <tr style="text-align: center;">
        <td>
          <%= link_to(edit_shipping_company_vehicle_path(@shipping_company.id, v.id)) do %>
            <%= v.make %> <%= v.model %> <%= v.year %>
          <% end %>
        </td>
        <td><%= v.id_plate %></td>
        <td><%= v.load_capacity %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Nenhum veículo cadastrado.</p>
<% end %>

<%= link_to 'Voltar', shipping_company_path(@shipping_company.id) %>

app/views/vehicles/new.html.erb
<h2>Transportadora <%= @shipping_company.brand_name %>: Cadastrar novo veículo</h2>

<%= render partial: 'form' %>

<%= link_to 'Voltar', shipping_company_vehicles_path %>