config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  devise_for :users, path: 'users', controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root to: 'home#index'

  resources :shipping_companies, only: [:index, :show, :new, :create, :edit, :update] do

    resources :vehicles, only: [:index, :new, :create, :edit, :update]
    resources :volume_prices, only: [:index, :new, :create]
    resources :weight_prices, only: [:index, :new, :create]
    resources :delivery_times, only: [:index, :new, :create]
    get 'sc_orders', on: :member
    collection do
      get 'budget_form'
      get 'budget_search'
      get 'tracking_form'
      get 'tracking_search'
    end
    resources :orders, only: [:show, :update] do
      resources :route_updates, only: [:index, :new, :create]
      member do
        post 'flag_button'
        patch 'approve'
      end
    end

  end



  resources :orders, only: [:index, :new, :create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreightApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="style.css">
  </head>

  <body>
    <header>
      <h1>Sistema de Fretes</h1>
      <nav>
        <%= link_to 'Home', root_path %>  |
        <%= link_to 'Transportadoras', shipping_companies_path %>  |
        <% if user_signed_in? && current_user.shipping_company != nil %>
          <%= link_to 'Minha Transportadora', shipping_company_path(current_user.shipping_company_id) %> |
        <% end %>
        <%= link_to 'Ordens de Serviço', orders_path %> |
        <% if user_signed_in? && current_user.shipping_company != nil %>
          <%= link_to 'Minhas Ordens de Serviço', sc_orders_shipping_company_path(current_user.shipping_company_id) %> |
        <% end %>
        <%= link_to 'Rastreamento de Entrega',  tracking_form_shipping_companies_path %> |
        <% if admin_signed_in? %>
          <%= link_to 'Consulta de Preços', budget_form_shipping_companies_path %> |
          <%= current_admin.email %>
          <%= button_to 'Sair', destroy_admin_session_path, method: :delete %>
        <% elsif user_signed_in? %>
          <%= current_user.email %>
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Fazer Login como Admin', new_admin_session_path %> |
          <%= link_to 'Fazer Login como Usuário', new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <main>
      <div>
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>